language: php
php:
  - 5.5
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: 9d6a84f7ca4f0a4a7db8d015908d8c9267fb04802a9f9d8a64531d46ff501564
before_script:
  - sed -i '/phpdoc/d' composer.json
  - composer install
script:
  - phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/* --standard=PSR2 .
  - ./vendor/bin/phpcs --standard=./vendor/uwdoem/standard/ruleset.xml src
after_script:
  - vendor/bin/test-reporter